#!/usr/bin/env bash
# Configures Nginx to run as nginx user on port 8080

# Change user to nginx in nginx.conf
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Change port to 8080
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80/listen [::]:8080/g' /etc/nginx/sites-enabled/default

# Kill and restart nginx
pkill nginx
sleep 1
nginx

