#!/usr/bin/env bash
# Run nginx as the nginx user and make it listen on port 8080
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
