#!/usr/bin/env bash
# Configures Apache server inside container to return "Hello Holberton"

if service apache2 status > /dev/null 2>&1; then
    service apache2 restart > /dev/null 2>&1
else
    service apache2 start > /dev/null 2>&1
fi

echo "Hello Holberton" > /var/www/html/index.html

echo "apache2 is running"

