#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 server
apt-get update -y
apt-get install haproxy -y

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    log /dev/log local0
    maxconn 2048
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7034-web-01 18.233.158.107:80 check
    server 7034-web-02 44.201.84.254:80 check
HAPROXY

service haproxy restart