#!/usr/bin/env bash
apt-get update -y
apt-get install -y haproxy
cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    daemon
defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server web-01 18.233.158.107:80 check
    server web-02 44.201.84.254:80 check
HAPROXY
service haproxy restart

