#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 instead of 8080

# Use sed to replace '8080' with '80' in the default config file
sed -i 's/8080/80/g' /etc/nginx/sites-available/default

service nginx restart
