#!/usr/bin/env bash
# Fixes Nginx to listen on port 80

# Make sure nginx is installed
apt-get install -y nginx 2>/dev/null

# Make sure port 80 is configured
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:8080/listen [::]:80/g' /etc/nginx/sites-available/default

# Start nginx
service nginx start

