#!/usr/bin/env bash
# Installs and configures Nginx on Ubuntu

apt-get update
apt-get install -y nginx

# Add Holberton School to default page
echo "Holberton School" > /var/www/html/index.html

# Allow port 80
ufw allow 'Nginx HTTP'

# Restart nginx without systemctl
service nginx restart
#!/usr/bin/env bash
# Installs and configures Nginx on Ubuntu

apt-get update
apt-get install -y nginx

# Add Holberton School to default page
echo "Holberton School" > /var/www/html/index.html

# Allow port 80
ufw allow 'Nginx HTTP'

# Restart nginx without systemctl
service nginx restart

