#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

apt-get update
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add 301 redirect and custom 404 page
sed -i '/server_name _;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart

